#!/usr/bin/env python3
"""
Generate a C++ header of ML-DSA-44 known-answer test vectors for the HLS testbench,
sourced directly from the official NIST ACVP-Server KAT files
(usnistgov/ACVP-Server, gen-val/json-files/ML-DSA-{sigGen,sigVer}-FIPS204).

Run fetch_vectors.sh first to download the raw vectors into ./vectors/, then run this
script; it writes tb_vectors.h next to it. No third-party dependencies (stdlib only).

Selected groups:
  sigVer tgId=1  (external, pure, ML-DSA-44): pk, message, context, signature -> testPassed
      Exercises k_verify's fixed ctx/domain-separation path end-to-end.
  sigGen tgId=7  (internal, deterministic=true,  ML-DSA-44): mu, sk -> signature
      rnd is implicitly all-zero (Algorithm 2 step 5's deterministic substitution) -
      exercises k_sign/dataflow() with the "kept off" default rnd behavior.
  sigGen tgId=19 (internal, deterministic=false, ML-DSA-44): mu, rnd, sk -> signature
      Exercises the new real rnd wiring with genuine hedged values.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
VECTORS = ROOT / "vectors"
OUT = ROOT / "tb_vectors.h"

PARAM_SET = "ML-DSA-44"


def load(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def hexbytes(s):
    return bytes.fromhex(s) if s else b""


def index_expected(expected_json, tg_id):
    for g in expected_json["testGroups"]:
        if g["tgId"] == tg_id:
            return {t["tcId"]: t for t in g["tests"]}
    raise KeyError(f"tgId {tg_id} not found in expected results")


def find_group(prompt_json, tg_id):
    for g in prompt_json["testGroups"]:
        if g["tgId"] == tg_id:
            assert g["parameterSet"] == PARAM_SET, (tg_id, g["parameterSet"])
            return g
    raise KeyError(f"tgId {tg_id} not found in prompt")


def c_array(name, data):
    if len(data) == 0:
        data = b"\x00"  # C++ disallows zero-length arrays; length-0 cases just never read it
    body = ", ".join(f"0x{b:02X}" for b in data)
    return f"static const uint8_t {name}[{len(data)}] = {{{body}}};\n"


def main():
    sigver_prompt = load(VECTORS / "ML-DSA-sigVer-FIPS204" / "prompt.json")
    sigver_expected = load(VECTORS / "ML-DSA-sigVer-FIPS204" / "expectedResults.json")
    siggen_prompt = load(VECTORS / "ML-DSA-sigGen-FIPS204" / "prompt.json")
    siggen_expected = load(VECTORS / "ML-DSA-sigGen-FIPS204" / "expectedResults.json")

    ver_group = find_group(sigver_prompt, 1)
    ver_exp = index_expected(sigver_expected, 1)

    gen_det_group = find_group(siggen_prompt, 7)
    gen_det_exp = index_expected(siggen_expected, 7)
    gen_hedge_group = find_group(siggen_prompt, 19)
    gen_hedge_exp = index_expected(siggen_expected, 19)

    lines = []
    lines.append("// AUTO-GENERATED by gen_vectors.py - do not edit by hand.")
    lines.append("// Source: NIST ACVP-Server (usnistgov/ACVP-Server), gen-val/json-files/")
    lines.append("//   ML-DSA-sigVer-FIPS204 (tgId=1, external/pure, ML-DSA-44)")
    lines.append("//   ML-DSA-sigGen-FIPS204 (tgId=7 deterministic=true, tgId=19 deterministic=false, internal, ML-DSA-44)")
    lines.append("#ifndef TB_VECTORS_H")
    lines.append("#define TB_VECTORS_H")
    lines.append("#include <stdint.h>")
    lines.append("")

    # ---- sigVer cases ----
    ver_entries = []
    for i, tc in enumerate(ver_group["tests"]):
        pk = hexbytes(tc["pk"])
        msg = hexbytes(tc["message"])
        ctx = hexbytes(tc["context"])
        sig = hexbytes(tc["signature"])
        expected = ver_exp[tc["tcId"]]["testPassed"]

        lines.append(c_array(f"ver_pk_{i}", pk))
        lines.append(c_array(f"ver_msg_{i}", msg))
        lines.append(c_array(f"ver_ctx_{i}", ctx))
        lines.append(c_array(f"ver_sig_{i}", sig))
        ver_entries.append(
            f'  {{ "sigVer tc{tc["tcId"]}", {tc["tcId"]}, ver_pk_{i}, ver_msg_{i}, {len(msg)}, '
            f'ver_ctx_{i}, {len(ctx)}, ver_sig_{i}, {"true" if expected else "false"} }},'
        )

    lines.append("struct VerCase {")
    lines.append("    const char *label; unsigned tcId;")
    lines.append("    const uint8_t *pk;")
    lines.append("    const uint8_t *msg; unsigned mlen;")
    lines.append("    const uint8_t *ctx; unsigned ctxlen;")
    lines.append("    const uint8_t *sig;")
    lines.append("    bool expected;")
    lines.append("};")
    lines.append("static const VerCase VER_CASES[] = {")
    lines.extend(ver_entries)
    lines.append("};")
    lines.append("#define VER_CASES_COUNT (sizeof(VER_CASES)/sizeof(VER_CASES[0]))")
    lines.append("")

    # ---- sigGen cases (deterministic + hedged) ----
    sign_entries = []
    idx = 0
    for group, expected_map, is_hedged in (
        (gen_det_group, gen_det_exp, False),
        (gen_hedge_group, gen_hedge_exp, True),
    ):
        for tc in group["tests"]:
            sk = hexbytes(tc["sk"])
            mu = hexbytes(tc["mu"])
            rnd = hexbytes(tc["rnd"]) if is_hedged else bytes(32)  # off-by-default: all-zero rnd
            sig = hexbytes(expected_map[tc["tcId"]]["signature"])

            lines.append(c_array(f"sign_sk_{idx}", sk))
            lines.append(c_array(f"sign_mu_{idx}", mu))
            lines.append(c_array(f"sign_rnd_{idx}", rnd))
            lines.append(c_array(f"sign_sig_{idx}", sig))
            label = f'sigGen tc{tc["tcId"]} ({"hedged" if is_hedged else "deterministic/rnd=0"})'
            sign_entries.append(
                f'  {{ "{label}", {tc["tcId"]}, sign_sk_{idx}, sign_mu_{idx}, sign_rnd_{idx}, sign_sig_{idx} }},'
            )
            idx += 1

    lines.append("struct SignCase {")
    lines.append("    const char *label; unsigned tcId;")
    lines.append("    const uint8_t *sk;")
    lines.append("    const uint8_t *mu;")
    lines.append("    const uint8_t *rnd;")
    lines.append("    const uint8_t *expected_sig;")
    lines.append("};")
    lines.append("static const SignCase SIGN_CASES[] = {")
    lines.extend(sign_entries)
    lines.append("};")
    lines.append("#define SIGN_CASES_COUNT (sizeof(SIGN_CASES)/sizeof(SIGN_CASES[0]))")
    lines.append("")
    lines.append("#endif // TB_VECTORS_H")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({OUT.stat().st_size} bytes)")
    print(f"  sigVer cases:  {len(ver_entries)}")
    print(f"  sigGen cases:  {len(sign_entries)} ({len(gen_det_group['tests'])} deterministic + {len(gen_hedge_group['tests'])} hedged)")


if __name__ == "__main__":
    main()
